name: Build and deploy to Anypoint Exchange
 
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    uses: jpontdia/mule-common-devops/.github/workflows/mulesoft.yml@main
    with:
      keyvault-key: jpworks-keyvault
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}